#!/usr/bin/env bash

# Install nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Configure nginx to listen on port 80 and return "Hello World!"
sudo echo "Hello World!" > /var/www/html/index.html
sudo sed -i 's|root /var/www/html;|root /var/www/html;\n\tindex index.html;|' /etc/nginx/sites-available/default
sudo service nginx restart
