#!/usr/bin/env bash
## Configure nginx server to listen on port 80

# remove the default Nginx configuration file
rm /etc/nginx/sites-enabled/default
# configure nginx to listen on port 80 for all active IPV4 IPS
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx restart